import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const clashDisplay = localFont({
	src: "./fonts/ClashDisplay-Variable.woff2",
	variable: "--font-clash-display",
	weight: "200 700",
})

export const metadata: Metadata = {
	title: "BentoCase",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${clashDisplay.className} antialiased`}>
				{children}
			</body>
		</html>
	)
}
